//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taskool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignacion_Archivo
    {
        public int id { get; set; }
        public int idAsignacion { get; set; }
        public string nombreArchivo { get; set; }
        public string pathArchivo { get; set; }
        public int numDescargas { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public byte estadoArchivo { get; set; }
        public Nullable<System.DateTime> fechaEliminacion { get; set; }
    
        public virtual Asignacion Asignacion { get; set; }
    }
}
