//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taskool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asignacion
    {
        public Asignacion()
        {
            this.Asignacion_Archivo = new HashSet<Asignacion_Archivo>();
        }
    
        public int id { get; set; }
        public int idGrupo { get; set; }
        public int idUsuarioAsignacion { get; set; }
        public string titulo { get; set; }
        public string detalle { get; set; }
        public int idAsignatura { get; set; }
        public System.DateTime fechaAsignacion { get; set; }
        public System.DateTime fechaEntrega { get; set; }
        public short idTipoAsignacion { get; set; }
        public System.DateTime fechaRegistro { get; set; }
        public byte estadoAsignacion { get; set; }
        public Nullable<System.DateTime> fechaModificacion { get; set; }
        public Nullable<System.DateTime> fechaEliminacion { get; set; }
    
        public virtual ICollection<Asignacion_Archivo> Asignacion_Archivo { get; set; }
        public virtual Grupo Grupo { get; set; }
        public virtual TipoAsignacion TipoAsignacion { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
