//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taskool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comunicado
    {
        public int id { get; set; }
        public int idUsuarioComunicado { get; set; }
        public int idGrupo { get; set; }
        public System.DateTime fechaComunicado { get; set; }
        public System.DateTime fechaVigencia { get; set; }
        public string titulo { get; set; }
        public string urlImagen { get; set; }
        public string url1 { get; set; }
        public string url2 { get; set; }
        public string detalle { get; set; }
        public byte estadoComunicado { get; set; }
        public System.DateTime fechaRegistro { get; set; }
    
        public virtual Grupo Grupo { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
