//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taskool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo_Restriccion
    {
        public int idGrupo { get; set; }
        public short idTipoAsignacion { get; set; }
        public short idTipoRestriccion { get; set; }
        public short numMaximoDia { get; set; }
    
        public virtual Grupo Grupo { get; set; }
        public virtual Tipo_Restriccion Tipo_Restriccion { get; set; }
        public virtual TipoAsignacion TipoAsignacion { get; set; }
    }
}
