//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taskool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Grupo_Evaluacion
    {
        public int id { get; set; }
        public int idGrupo { get; set; }
        public System.DateTime fechaInicial { get; set; }
        public System.DateTime fechaFinal { get; set; }
    
        public virtual Grupo Grupo { get; set; }
    }
}
