//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taskool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institucion
    {
        public Institucion()
        {
            this.Grupo = new HashSet<Grupo>();
            this.Usuario = new HashSet<Usuario>();
        }
    
        public int id { get; set; }
        public string nit { get; set; }
        public string razonSocial { get; set; }
        public string direccion { get; set; }
        public string telefono1 { get; set; }
        public string telefono2 { get; set; }
        public int idCiudad { get; set; }
        public byte estadoInstitucion { get; set; }
        public System.DateTime fechaRegistro { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual ICollection<Grupo> Grupo { get; set; }
        public virtual ICollection<Usuario> Usuario { get; set; }
    }
}
