//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taskool.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TareasEntities : DbContext
    {
        public TareasEntities()
            : base("name=TareasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Asignacion> Asignacion { get; set; }
        public DbSet<Asignacion_Archivo> Asignacion_Archivo { get; set; }
        public DbSet<Asignatura> Asignatura { get; set; }
        public DbSet<Calendario> Calendario { get; set; }
        public DbSet<Categoria> Categoria { get; set; }
        public DbSet<Ciudad> Ciudad { get; set; }
        public DbSet<Comunicado> Comunicado { get; set; }
        public DbSet<Grado> Grado { get; set; }
        public DbSet<GradoN> GradoN { get; set; }
        public DbSet<Grupo> Grupo { get; set; }
        public DbSet<Grupo_Evaluacion> Grupo_Evaluacion { get; set; }
        public DbSet<Grupo_Restriccion> Grupo_Restriccion { get; set; }
        public DbSet<Institucion> Institucion { get; set; }
        public DbSet<Perfil> Perfil { get; set; }
        public DbSet<Tipo_Restriccion> Tipo_Restriccion { get; set; }
        public DbSet<TipoAsignacion> TipoAsignacion { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    }
}
