//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taskool.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.Asignacion = new HashSet<Asignacion>();
            this.Comunicado = new HashSet<Comunicado>();
            this.Grupo = new HashSet<Grupo>();
        }
    
        public int id { get; set; }
        public int idInstitucion { get; set; }
        public string nombreUsuario { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public byte estadoUsuario { get; set; }
        public System.DateTime fechaRegistro { get; set; }
    
        public virtual ICollection<Asignacion> Asignacion { get; set; }
        public virtual ICollection<Comunicado> Comunicado { get; set; }
        public virtual Institucion Institucion { get; set; }
        public virtual ICollection<Grupo> Grupo { get; set; }
    }
}
